import requests
import pandas as pd
from datetime import datetime
import re
from html import unescape
import os
import smtplib
from email.mime.text import MIMEText

# =========================================================
# CONFIG SECTION
# Change values here only
# =========================================================

# TAB OPTIONS (InvestorGain API Tabs)
# -----------------------------------
# "open"            → All active IPOs
# "closing-today"   → IPOs closing today
# "current"         → Upcoming IPOs
# "ipo"             → Mainboard IPOs only
# "close"           → Closed IPOs

TAB = "open"   # Change to "closing-today" later


# GMP FILTER
# -----------------------------------
# -1 → Test mode (includes ₹0 GMP)
#  0 → Production mode (only positive GMP)

GMP_FILTER = -1


# =========================================================
# EMAIL CONFIG (Loaded from GitHub Secrets)
# =========================================================

EMAIL_USER = os.getenv("EMAIL_USER")
EMAIL_PASS = os.getenv("EMAIL_PASS")
EMAIL_TO = os.getenv("EMAIL_TO")


# =========================================================
# HTML EMAIL BUILDER FUNCTION
# =========================================================

def build_html_table(df, title):

    html_table = df.to_html(index=False)

    html_body = f"""
    <html>
    <head>
    <style>
        body {{
            font-family: Arial, sans-serif;
            background-color: #f6f8fa;
            padding: 20px;
        }}

        .card {{
            background-color: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 6px rgba(0,0,0,0.1);
        }}

        h2 {{
            color: #2E86C1;
        }}

        table {{
            border-collapse: collapse;
            width: 100%;
        }}

        th, td {{
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
        }}

        th {{
            background-color: #2E86C1;
            color: white;
        }}

        tr:nth-child(even) {{
            background-color: #f2f2f2;
        }}

        .footer {{
            margin-top: 20px;
            font-size: 12px;
            color: gray;
        }}
    </style>
    </head>

    <body>

        <div class="card">
            <h2>{title}</h2>
            {html_table}
            <div class="footer">
                Generated by IPO Notifier Agent
            </div>
        </div>

    </body>
    </html>
    """

    return html_body


# =========================================================
# BUILD DYNAMIC API URL
# =========================================================

today = datetime.now()

month = today.month
year = today.year

if month >= 4:
    fy = f"{year}-{str(year+1)[-2:]}"
else:
    fy = f"{year-1}-{str(year)[-2:]}"

URL = (
    f"https://webnodejs.investorgain.com/cloud/new/report/"
    f"data-read/331/1/{month}/{year}/{fy}/0/{TAB}"
)

HEADERS = {"User-Agent": "Mozilla/5.0"}

print("\n====================================")
print("📡 IPO Notifier Agent Running")
print("====================================\n")

print(f"TAB MODE: {TAB}")
print(f"GMP FILTER: > {GMP_FILTER}")
print("URL:", URL, "\n")


# =========================================================
# FETCH API DATA
# =========================================================

response = requests.get(URL, headers=HEADERS)
response.raise_for_status()

data = response.json()
ipo_rows = data.get("reportTableData", [])

print(f"Total IPOs fetched: {len(ipo_rows)}\n")


# =========================================================
# PARSE DATA
# =========================================================

parsed_data = []

for ipo in ipo_rows:

    name = ipo.get("~ipo_name", "N/A")
    gmp_html = ipo.get("GMP", "")

    gmp_text = unescape(gmp_html)
    gmp_text = re.sub(r'<.*?>', '', gmp_text)

    gmp_match = re.search(r'(-?\d+)', gmp_text)
    gmp_value = int(gmp_match.group(1)) if gmp_match else 0

    subscription = ipo.get("Sub", "N/A")
    close_date = ipo.get("~Srt_Close", "N/A")

    parsed_data.append([
        name,
        gmp_value,
        subscription,
        close_date
    ])


# =========================================================
# DATAFRAME
# =========================================================

df = pd.DataFrame(
    parsed_data,
    columns=["IPO Name", "GMP", "Subscription", "Close Date"]
)

print("====================================")
print("📊 RAW IPO DATA")
print("====================================\n")

if df.empty:
    print("No IPOs found.\n")


# =========================================================
# FILTER LOGIC
# =========================================================

filtered_df = df[df["GMP"] > GMP_FILTER]

print("====================================")
print("🧪 FILTERED IPO DATA")
print("====================================\n")

if filtered_df.empty:
    print("No IPO matches GMP filter. No email sent.\n")
    exit()

print(filtered_df.to_string(index=False))


# =========================================================
# BUILD HTML EMAIL
# =========================================================

html_body = build_html_table(
    filtered_df,
    "📊 IPO Alert - Daily Digest"
)

msg = MIMEText(html_body, "html")
msg["Subject"] = "IPO Alert — GMP > 0"
msg["From"] = EMAIL_USER
msg["To"] = EMAIL_TO


# =========================================================
# SEND EMAIL
# =========================================================

print("\nSending email alert...\n")

server = smtplib.SMTP("smtp.gmail.com", 587)
server.starttls()
server.login(EMAIL_USER, EMAIL_PASS)
server.send_message(msg)
server.quit()

print("Email sent successfully ✅\n")
print("====================================\n")
