# =========================================================
# HTML BUILDER
# Converts dataframe → styled HTML email section
# =========================================================

def build_html_table(df, title):

    html_table = df.to_html(index=False)

    html_body = f"""
    <html>
    <head>
    <style>
        body {{
            font-family: Arial, sans-serif;
            background-color: #f6f8fa;
            padding: 20px;
        }}

        .card {{
            background-color: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 6px rgba(0,0,0,0.1);
            margin-bottom: 20px;
        }}

        h2 {{
            color: #2E86C1;
        }}

        table {{
            border-collapse: collapse;
            width: 100%;
        }}

        th, td {{
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
        }}

        th {{
            background-color: #2E86C1;
            color: white;
        }}

        tr:nth-child(even) {{
            background-color: #f2f2f2;
        }}

        .footer {{
            margin-top: 20px;
            font-size: 12px;
            color: gray;
        }}
    </style>
    </head>

    <body>
        <div class="card">
            <h2>{title}</h2>
            {html_table}
            <div class="footer">
                Generated by Daily Digest Agent
            </div>
        </div>
    </body>
    </html>
    """

    return html_body
